### ISSUE TITLE
Fresh install of Ubuntu 24.04 LTS doesn't auto enroll in Pro

### ISSUE THREAD

**Issue by local-optimum** [canonical/ubuntu-pro-for-wsl#752] opened 2024-05-02 12:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and found none that matched mine

### Describe the issue

I downloaded the latest Ubuntu 24.04 LTS app from the Windows store.

I already had v0.1.2-247-gedcec808 (would be good to make this string copy-pastable btw) of the Pro app installed with my token attached.

Expectation... the new instance would be auto enrolled in Pro automatically
Reality... running pro status after install and after a full wsl restart showed that the instance was unattached.

### Steps to reproduce it

Install the Pro app.

Submit pro token to the app and get 'subscription active' message.

Install 24.04 LTS from the Windows store

Complete install

Run pro status

### Installed versions

* Windows version: *Run cmd /c ver* Microsoft Windows [Version 10.0.22631.3447]
* WSL version: *wsl --status* 2
* Windows application version: Open Pro for Windows GUI, check version in status bar. v0.1.2-247-gedcec808
* WSL distribution: Name of the Ubuntu distribution you are using: Ubuntu 24.04 LTS
* WSL OS: (`/etc/os-release`) in the wsl instance
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
* ubuntu wsl service version: (`apt policy wsl-pro-service` output)
wsl-pro-service:
  Installed: 0.1.4
  Candidate: 0.1.4
  Version table:
 *** 0.1.4 500
        500 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status

### System logs

May 02 12:49:57 Lenovo-T5 systemd[1]: Starting wsl-pro.service - Bridge to Ubuntu Pro agent on Windows...
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: INFO Starting WSL Pro Service version v0.1.4
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: DEBUG Debug mode is enabled
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: DEBUG Building new daemon
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: DEBUG Ready state sent to systemd
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: INFO Daemon: connecting to Windows Agent
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: DEBUG Updated systemd status to "Connecting"
May 02 12:49:57 Lenovo-T5 systemd[1]: Started wsl-pro.service - Bridge to Ubuntu Pro agent on Windows.
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: INFO Daemon: starting connection to Windows Agent via XXX
May 02 12:49:57 Lenovo-T5 wsl-pro-service[253]: WARNING Daemon: could not connect to Windows Agent: XXX
...
May 02 12:50:00 Lenovo-T5 wsl-pro-service[253]: DEBUG Updated systemd status to "Connecting"
May 02 12:50:00 Lenovo-T5 wsl-pro-service[253]: DEBUG Updated systemd status to "Stopped"
May 02 12:50:00 Lenovo-T5 wsl-pro-service[253]: ERROR context.Background could not connect to Windows Agent: could not get address: coud not find address>
May 02 12:50:00 Lenovo-T5 systemd[1]: wsl-pro.service: Main process exited, code=exited, status=1/FAILURE
May 02 12:50:00 Lenovo-T5 systemd[1]: wsl-pro.service: Failed with result 'exit-code'.
May 02 12:50:03 Lenovo-T5 systemd[1]: wsl-pro.service: Scheduled restart job, restart counter is at 1.
May 02 12:50:03 Lenovo-T5 systemd[1]: Starting wsl-pro.service - Bridge to Ubuntu Pro agent on Windows...
May 02 12:50:03 Lenovo-T5 wsl-pro-service[571]: INFO Starting WSL Pro Service version v0.1.4
May 02 12:50:03 Lenovo-T5 wsl-pro-service[571]: DEBUG Debug mode is enabled
May 02 12:50:03 Lenovo-T5 wsl-pro-service[571]: DEBUG Building new daemon

Logs are:

======= STARTUP =======
time=2024-05-01T08:48:29+01:00 level=info msg=Version: v0.1.2-247-gedcec808
time=2024-05-01T08:48:29+01:00 level=warning msg=config: could not validate subscription against Microsoft Store: could not get the Ubuntu Pro token from the Microsoft Store: couldn't get a Microsoft-Store-provided Ubuntu Pro token: couldn't download auth token from the contracts server: server replied with an error: Code 404, 404 page not found

### Double check your logs

- [X] I have redacted any sensitive information from the logs

**Comment by jibel** [comment] 2024-09-09 16:05
Thanks for you report.

All the components changes a lot since May 2nd and I couldn't reproduce the issue. 
I'm closing this report. Feel free to reopen if it is still an issue for you.

**Closed by jibel** 2024-09-09 16:05 UTC
Labels: bug, jira
